apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: social-media
data:
  SPRING_PROFILES_ACTIVE: "prod"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "socialmedia"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: social-media
type: Opaque
stringData:
  DB_USERNAME: postgres
  DB_PASSWORD: postgres123
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: social-media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: social-media-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
          env:
            - name: JAVA_OPTS
              value: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: social-media
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
