# Updated Frontend with real Next.js images

# Core App (Shell - Main entry point)
apiVersion: v1
kind: ConfigMap
metadata:
  name: core-config
  namespace: social-media
data:
  NODE_ENV: "production"
  AUTH_SERVICE_URL: "http://auth:3001"
  SOCIAL_SERVICE_URL: "http://social:3002"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: core
  namespace: social-media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core
  template:
    metadata:
      labels:
        app: core
    spec:
      containers:
        - name: core
          image: social-media-core:latest
          imagePullPolicy: Never  # Use local image
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: core-config
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: core
  namespace: social-media
spec:
  selector:
    app: core
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
---
# Auth App
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: social-media
data:
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "http://api-gateway:8080"
  KEYCLOAK_URL: "http://keycloak:8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: social-media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: social-media-auth:latest
          imagePullPolicy: Never  # Use local image
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: auth-config
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /login
              port: 3001
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /login
              port: 3001
            initialDelaySeconds: 15
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: social-media
spec:
  selector:
    app: auth
  ports:
    - port: 3001
      targetPort: 3001
  type: ClusterIP
---
# Social App
apiVersion: v1
kind: ConfigMap
metadata:
  name: social-config
  namespace: social-media
data:
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "http://api-gateway:8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: social
  namespace: social-media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: social
  template:
    metadata:
      labels:
        app: social
    spec:
      containers:
        - name: social
          image: social-media-social:latest
          imagePullPolicy: Never  # Use local image
          ports:
            - containerPort: 3002
          envFrom:
            - configMapRef:
                name: social-config
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 3002
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3002
            initialDelaySeconds: 15
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: social
  namespace: social-media
spec:
  selector:
    app: social
  ports:
    - port: 3002
      targetPort: 3002
  type: ClusterIP